// Generated by Haxe 5.0.0-alpha.1+1423a5f
(function ($global) { "use strict";
Math.__name__ = "Math";
var Std = function() { };
Std.__name__ = "Std";
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var creeling_ASTNode = function(kind,varID,typeName,methodID,children,thenBlock,elseBlock) {
	this.elseBlock = null;
	this.thenBlock = null;
	this.children = null;
	this.methodID = null;
	this.typeName = null;
	this.kind = kind;
	this.varID = varID;
	if(typeName != null) {
		this.typeName = typeName;
	}
	if(methodID != null) {
		this.methodID = methodID;
	}
	if(children != null) {
		this.children = children;
	}
	if(thenBlock != null) {
		this.thenBlock = thenBlock;
	}
	if(elseBlock != null) {
		this.elseBlock = elseBlock;
	}
};
creeling_ASTNode.__name__ = "creeling.ASTNode";
var creeling_CreelingTyper = function() {
	this.specializedClones = new haxe_ds_StringMap();
	this.context = new creeling_FlowContext();
};
creeling_CreelingTyper.__name__ = "creeling.CreelingTyper";
creeling_CreelingTyper.prototype = {
	specializeAndCheck: function(nodes) {
		var outputInstructions = [];
		var len = nodes.length;
		var node;
		var _g = 0;
		var _g1 = len;
		while(_g < _g1) {
			var i = _g++;
			node = nodes[i];
			switch(node.kind) {
			case "ALLOC":
				var this1 = this.context.variables;
				var key = node.varID;
				var value = new creeling_VariableTrack(node.varID,node.typeName != null ? node.typeName : "Unknown",1);
				this1.h[key] = value;
				outputInstructions.push("ALLOC_OBJ var_" + node.varID + "<" + node.typeName + ">");
				break;
			case "BLOCK":
				if(node.children != null) {
					outputInstructions = outputInstructions.concat(this.specializeAndCheck(node.children));
				}
				break;
			case "FIELD_STORE":
				var track = this.context.variables.h[node.varID];
				if(track != null) {
					track.state = 2;
					outputInstructions.push("UPGRADE_TO_RUNTIME_RC var_" + node.varID);
				}
				break;
			case "IF_ELSE":
				var thenSnapshot = this.context.clone();
				var elseSnapshot = this.context.clone();
				this.context = thenSnapshot;
				var thenInstructions = node.thenBlock != null ? this.specializeAndCheck(node.thenBlock) : [];
				this.context = elseSnapshot;
				var elseInstructions = node.elseBlock != null ? this.specializeAndCheck(node.elseBlock) : [];
				this.context = this.mergeBranchUnification(thenSnapshot,elseSnapshot);
				outputInstructions.push("START_BRANCH_IF");
				outputInstructions = outputInstructions.concat(thenInstructions);
				outputInstructions.push("BRANCH_ELSE");
				outputInstructions = outputInstructions.concat(elseInstructions);
				outputInstructions.push("END_BRANCH");
				break;
			case "METHOD_CALL":
				var track1 = this.context.variables.h[node.varID];
				var argState = track1 != null && track1.state == 1 ? "Owned" : "Borrow";
				var variantSignature = node.methodID + "_Varient_" + argState;
				if(!Object.prototype.hasOwnProperty.call(this.specializedClones.h,node.methodID)) {
					this.specializedClones.h[node.methodID] = [];
				}
				this.specializedClones.h[node.methodID].push(variantSignature);
				outputInstructions.push("CALL_METHOD " + variantSignature + " via var_" + node.varID);
				break;
			case "VAR_ACCESS":
				var track2 = this.context.variables.h[node.varID];
				if(track2 != null && track2.state == 1) {
					outputInstructions.push("READ_OWNED var_ " + node.varID);
				} else {
					outputInstructions.push("READ_BORROW var_ " + node.varID);
				}
				break;
			}
			this.evaluateLivenessPruning(node.varID,i,nodes,outputInstructions);
		}
		return outputInstructions;
	}
	,mergeBranchUnification: function(thenCtx,elseCtx) {
		var merged = new creeling_FlowContext();
		var id = thenCtx.variables.keys();
		while(id.hasNext()) {
			var id1 = id.next();
			var thenTrack = thenCtx.variables.h[id1];
			var elseTrack = elseCtx.variables.h[id1];
			if(elseTrack == null) {
				continue;
			}
			if(thenTrack.state == 2 || elseTrack.state == 2) {
				var this1 = merged.variables;
				var value = new creeling_VariableTrack(id1,thenTrack.type,2);
				this1.h[id1] = value;
			} else if(thenTrack.state == 1 && elseTrack.state == 1) {
				var this2 = merged.variables;
				var value1 = new creeling_VariableTrack(id1,thenTrack.type,1);
				this2.h[id1] = value1;
			} else {
				var this3 = merged.variables;
				var value2 = new creeling_VariableTrack(id1,thenTrack.type,2);
				this3.h[id1] = value2;
			}
		}
		return merged;
	}
	,evaluateLivenessPruning: function(varID,currentIdx,totalStream,instructions) {
		var track = this.context.variables.h[varID];
		if(track == null || track.state == null || track.state != 1) {
			return;
		}
		var isUsedLater = false;
		var _g = currentIdx + 1;
		var _g1 = totalStream.length;
		while(_g < _g1) {
			var i = _g++;
			if(totalStream[i].varID == varID) {
				isUsedLater = true;
				break;
			}
		}
		if(!isUsedLater) {
			instructions.push(" LFR3_FREE var_" + varID);
			this.context.variables.remove(varID);
		}
	}
};
var creeling_FlowContext = function() {
	this.variables = new haxe_ds_IntMap();
};
creeling_FlowContext.__name__ = "creeling.FlowContext";
creeling_FlowContext.prototype = {
	clone: function() {
		var newCtx = new creeling_FlowContext();
		var k = this.variables.keys();
		while(k.hasNext()) {
			var k1 = k.next();
			var v = this.variables.h[k1];
			var this1 = newCtx.variables;
			var value = new creeling_VariableTrack(v.id,v.type,v.state);
			this1.h[k1] = value;
		}
		return newCtx;
	}
};
var creeling_Test = function() { };
creeling_Test.__name__ = "creeling.Test";
creeling_Test.main = function() {
	var program = [new creeling_ASTNode("ALLOC",101,"MathVector",null,null,null,null),new creeling_ASTNode("VAR_ACCESS",101,null,null,null,null,null),new creeling_ASTNode("IF_ELSE",0,null,null,null,[new creeling_ASTNode("METHOD_CALL",101,null,"calculateLength",null,null,null)],[new creeling_ASTNode("FIELD_STORE",101,null,null,null,null,null)])];
	var typer = new creeling_CreelingTyper();
	var compiledInstructions = typer.specializeAndCheck(program);
	console.log("src/creeling/Test.hx:13:","Generated Annotate Bytecode Stream:");
	var _g = 0;
	while(_g < compiledInstructions.length) {
		var inst = compiledInstructions[_g];
		++_g;
		console.log("src/creeling/Test.hx:14:"," - " + inst);
	}
	console.log("src/creeling/Test.hx:15:","\nGenerated Specialied Function Map:");
	var h = typer.specializedClones.h;
	var origin_h = h;
	var origin_keys = Object.keys(h);
	var origin_length = origin_keys.length;
	var origin_current = 0;
	while(origin_current < origin_length) {
		var origin = origin_keys[origin_current++];
		console.log("src/creeling/Test.hx:16:"," - Method: " + origin + " cloned variant: " + Std.string(typer.specializedClones.h[origin]));
	}
};
var creeling_VariableTrack = function(id,type,state) {
	this.id = id;
	this.type = type;
	this.state = state;
};
creeling_VariableTrack.__name__ = "creeling.VariableTrack";
var haxe_ds_IntMap = function() {
	this.h = { };
};
haxe_ds_IntMap.__name__ = "haxe.ds.IntMap";
haxe_ds_IntMap.prototype = {
	remove: function(key) {
		if(!this.h.hasOwnProperty(key)) {
			return false;
		}
		delete(this.h[key]);
		return true;
	}
	,keys: function() {
		var a = [];
		for( var key in this.h ) if(this.h.hasOwnProperty(key)) a.push(+key);
		return new haxe_iterators_ArrayIterator(a);
	}
};
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.__name__ = "haxe.ds.StringMap";
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = "haxe.iterators.ArrayIterator";
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = "js.Boot";
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
String.__name__ = "String";
Array.__name__ = "Array";
js_Boot.__toStr = ({ }).toString;
creeling_Test.main();
})({});
